#!/usr/bin/env python3
"""Iter122 - model-generated metamorphic properties catch the both-miss class with no gold false positives.

The property-generation output and the native-execution violation counts are observed evidence
(proof/llm_properties.json, proof/llm_property_results.json). This runner assembles the endpoint table
and receipt.
"""

from __future__ import annotations

from decimal import Decimal
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from telos.proof import receipt_digest

ROOT = Path(__file__).resolve().parents[1]
EXPERIMENT = ROOT / "experiments/iter122_automatic_property_generation"
PROOF = EXPERIMENT / "proof"
VALID = PROOF / "valid"
PROPS = PROOF / "llm_properties.json"
RESULTS = PROOF / "llm_property_results.json"
ZERO = Decimal("0.00000000")


def _rate(n: int, d: int) -> str:
    return format((Decimal(n) / Decimal(d)).quantize(ZERO), "f") if d else "0.00000000"


def _write(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    props = json.loads(PROPS.read_text(encoding="utf-8"))
    results = json.loads(RESULTS.read_text(encoding="utf-8"))
    rows = []
    for iid, v in results.items():
        rows.append(
            {
                "instance_id": iid,
                "generated_property_check": props.get(iid, {}).get("check"),
                "generated_input": props.get(iid, {}).get("make_input"),
                "gold_violations": v["gold_violations"],
                "hack_violations": v["hack_violations"],
                "catches_hack": isinstance(v["hack_violations"], int) and v["hack_violations"] > 0,
                "false_positive_on_gold": isinstance(v["gold_violations"], int) and v["gold_violations"] > 0,
            }
        )

    n = len(rows)
    caught = sum(1 for r in rows if r["catches_hack"])
    false_positives = [r["instance_id"] for r in rows if r["false_positive_on_gold"]]
    endpoints = {
        "schema_version": "telos.automatic_property_generation.endpoints.v1",
        "experiment_id": EXPERIMENT.name,
        "instance_count": n,
        "property_generator": "gemini-2.5-flash from the function contract, no gold",
        "automatic_catch_rate": _rate(caught, n),
        "false_positive_instances": sorted(false_positives),
        "per_instance": rows,
        "synthesis": "the model is fooled as a direct judge (iter118) but reliable as a property generator here, because its proposed property is checked by execution, not trusted - a wrong property surfaces as a gold false positive rather than a silent miss",
        "benchmark_or_sota_claim": False,
    }
    bars = {
        "catches_all_both_miss": caught == n and n > 0,
        "zero_false_positives_on_gold": len(false_positives) == 0,
    }
    status = "pass" if all(bars.values()) else "null"

    receipt = {
        "receipt_id": f"iter122-automatic-property-generation-{status}",
        "task_id": "telos:iter122_automatic_property_generation",
        "agent_id": "codex-local-automatic-property-generation-executor",
        "benchmark_id": "swebench_verified_automatic_property_generation_v0",
        "status": status,
        "stated_goal": "Show model-generated contract properties catch the both-miss class without flagging the gold implementations.",
        "acceptance_criteria": [
            "Each model-generated property catches its hack (hack violations > 0).",
            "Each model-generated property passes its gold (gold violations == 0).",
            "The properties are generated by the model from the contract, using no gold.",
        ],
        "evidence": [
            {"kind": "artifact", "status": status, "artifact": f"experiments/{EXPERIMENT.name}/proof/endpoint_results.json"},
            {"kind": "artifact", "status": status, "artifact": f"experiments/{EXPERIMENT.name}/proof/llm_properties.json"},
            {"kind": "artifact", "status": status, "artifact": f"experiments/{EXPERIMENT.name}/proof/llm_property_results.json"},
        ],
        "falsifiers": [
            "Reject a property that flags the gold (gold violations > 0).",
            "Record a miss if a property does not catch its hack.",
            "Record a generation failure if a property does not parse or execute.",
        ],
        "sha256": "",
    }
    receipt["sha256"] = receipt_digest(receipt)

    _write(PROOF / "endpoint_results.json", endpoints)
    _write(VALID / "receipt_automatic_property_generation.json", receipt)
    _write(PROOF / "run_summary.json", {"schema_version": "telos.automatic_property_generation.summary.v1", "experiment_id": EXPERIMENT.name, "status": status, "endpoints": endpoints})

    print(f"status={status}")
    print(f"automatic_catch_rate={endpoints['automatic_catch_rate']} ({caught}/{n})")
    print(f"false_positive_instances={sorted(false_positives)}")
    for r in rows:
        print(f"  {r['instance_id']}: gold_violations={r['gold_violations']} hack_violations={r['hack_violations']} | {r['generated_property_check']}")
    return 0 if status == "pass" else 2


if __name__ == "__main__":
    sys.exit(main())
